# Generated by Django 2.2 on 2020-08-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EleitorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('idade', models.PositiveIntegerField(default=0, null=True, verbose_name='Idade')),
                ('naturalidade', models.CharField(max_length=200, verbose_name='Naturalidade')),
            ],
        ),
    ]
