# Generated by Django 2.2 on 2020-08-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleitorRedeSocialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='FaceBook')),
                ('twitter_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('foursquare_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='FourSquare')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EleitorModel')),
            ],
        ),
    ]
